### ISSUE TITLE
update docs to reflect that patronictl edit-config needs to be run in quiet mode

### ISSUE THREAD

**Issue by markwort** [cybertec-postgresql/patroni-windows-packaging#16]
The python library cdiff (or as it's now known, ydiff) is hardwired to use `less`, it seems.
Regular Windows installs only have `more` and that is not enough.
When running edit-config in quiet mode, no diffs are generated, thus this option is currently the only one that works on windows.

Also think about whether a workaround should be pushed upstream (try cdiff, in case of exception try regular python diff...) or wether to create issue for ydiff and have them fix it. Or investigate what fixes it and open a PR for ydiff.

**Comment by pashagolub** [comment]
Fixed by https://github.com/zalando/patroni/pull/1696
