### ISSUE TITLE
Build dependencies failed during installation of Release v230803

### ISSUE THREAD

**Issue by geek7** [cybertec-postgresql/patroni-windows-packaging#60]
...
--- Installing Patroni packages ---
Looking in links: .patroni-packages
Processing c:\pes\patroni\.patroni-packages\urllib3-1.26.16-py2.py3-none-any.whl (from -r requirements.txt (line 1))
Processing c:\pes\patroni\.patroni-packages\boto3-1.28.2-py3-none-any.whl (from -r requirements.txt (line 2))
Processing c:\pes\patroni\.patroni-packages\pyyaml-6.0-cp311-cp311-win_amd64.whl (from -r requirements.txt (line 3))
Processing c:\pes\patroni\.patroni-packages\kazoo-2.9.0-py2.py3-none-any.whl (from -r requirements.txt (line 4))
Processing c:\pes\patroni\.patroni-packages\python-etcd-0.4.5.tar.gz (from -r requirements.txt (line 5))
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  ¦ exit code: 1
  ?-> [3 lines of output]
      Looking in links: .patroni-packages
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.8.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
¦ exit code: 1
?-> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Looking in links: .patroni-packages
...

**Comment by geek7** [comment]
Windows 2016
Powershell 7.3.7

**Comment by pashagolub** [comment]
Did you run it with admin permissions?

**Comment by geek7** [comment]
Yes

**Comment by geek7** [comment]
I had to install python-etcd, pysyncobj and ydiff manualy with pip install

**Comment by geek7** [comment]
- the module "setuptools" seams to be missing (not found with the given requirement) but I don't now if it's usefull for the package ?
- the modules "python-etcd", "pysyncobj" and "ydiff" where missing (requirements problem ?)
I don't notice download problem the requiered modules should be in the package for my point of view
