### ISSUE TITLE
Very hard to install without internet access, once installer is copied

### ISSUE THREAD

**Issue by einhverfr** [cybertec-postgresql/patroni-windows-packaging#70]
The PES system does include Python dependencies but there are several problems.

1.  There isn't a tested way to install all the dependencies.   I eventually figured out that the dependencies were in the `patroni/.patroni-packages` folder.  Additionally I figured out that `pip install --no-index --find-links ./` worked for the whl files but not for the .tgz packages.  
2. It isn't clear how to handle the .tar.gz files.  I ended up unpacking with 7zip and unpacking manually.

**Comment by pashagolub** [comment]
What are the steps to reproduce the bug? Any specific environment maybe?

**Comment by einhverfr** [comment]
Install current PES installer on an air-gapped Windows system and try to instal the Python dependencies from scratch.

Here;s what I figured out is missing:

- the wheel current wheel dependency
- the setuptools current wheel dependency
- A script to install all of the packages in .patroni-packages

The rest works pretty well.  Though it may be that there is something missing in the documentation in terms of this>

**Comment by einhverfr** [comment]
Wheel and setuptools are required because there are three dependencies which do not have whl files but instead tar.gz files.  And in Windows it is very hard to get this working without an internet connection.

**Comment by TakashiArakane** [comment]
How about adding the following to the patroni/.patroni-packages folder, and then install them in order with install.ps1?
I have also been testing this in an offline environment, and have confirmed that it works as expected with Release V240516.
(The versions may vary depending on the timing.)

* pip-24.0-py3-none-any.whl
* install-1.3.5-py3-none-any.whl
* setuptools-69.5.1-py3-none-any.whl
* wheel-0.43.0-py3-none-any.whl

```
python -m pip install --upgrade patroni\.patroni-packages\pip-24.0-py3-none-any.whl | Out-Default

pip3 install --no-index --find-links .patroni-pre-packages install
pip3 install --no-index --find-links .patroni-pre-packages setuptools
pip3 install --no-index --find-links .patroni-pre-packages wheel
```

**Comment by einhverfr** [comment]
This is great.

I think you need pip and wheel because those provide the installation tools for some of the other packages.

**Comment by pashagolub** [comment]
Cool then. @TakashiArakane would you please create a pull request?

Thanks in advance!
